ThAmCo.Events/Pages/Bookings/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ThAmCo.Events.Models;
using ThAmCo.Events.Models.DTO;

namespace ThAmCo.Events.Pages.Bookings
{
    public class CreateModel : PageModel
    {
        private readonly EventsDbContext _context;

        public CreateModel(EventsDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public BookGuestDto BookingDto { get; set; } = default!;

        public SelectList Guests { get; set; }
        public SelectList Events { get; set; }

        public async Task<IActionResult> OnGetAsync()
        {
            Guests = new SelectList(await _context.Guests.ToListAsync(), "Id", "Name");
            Events = new SelectList(await _context.Events.ToListAsync(), "Id", "Title");
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                Guests = new SelectList(await _context.Guests.ToListAsync(), "Id", "Name");
                Events = new SelectList(await _context.Events.ToListAsync(), "Id", "Title");
                return Page();
            }

            var existingBooking = await _context.GuestBookings
                .FirstOrDefaultAsync(gb => gb.GuestId == BookingDto.GuestId && gb.EventId == BookingDto.EventId);

            if (existingBooking != null)
            {
                ModelState.AddModelError(string.Empty, "This guest is already booked for the selected event.");
                Guests = new SelectList(await _context.Guests.ToListAsync(), "Id", "Name");
                Events = new SelectList(await _context.Events.ToListAsync(), "Id", "Title");
                return Page();
            }

            var guestBooking = new GuestBooking
            {
                GuestId = BookingDto.GuestId,
                EventId = BookingDto.EventId
            };

            _context.GuestBookings.Add(guestBooking);
            await _context.SaveChangesAsync();

            return RedirectToPage("/EventsList/Index");
        }
    }
}

ThAmCo.Events/Pages/Bookings/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ThAmCo.Events.Models;

namespace ThAmCo.Events.Pages.Bookings
{
    public class DeleteModel : PageModel
    {
        private readonly EventsDbContext _context;

        public DeleteModel(EventsDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public GuestBooking GuestBooking { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var guestbooking = await _context.GuestBookings.FirstOrDefaultAsync(m => m.EventId == id);

            if (guestbooking == null)
            {
                return NotFound();
            }
            else
            {
                GuestBooking = guestbooking;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var guestbooking = await _context.GuestBookings.FindAsync(id);
            if (guestbooking != null)
            {
                GuestBooking = guestbooking;
                _context.GuestBookings.Remove(GuestBooking);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

ThAmCo.Events/Pages/Bookings/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ThAmCo.Events.Models;

namespace ThAmCo.Events.Pages.Bookings
{
    public class DetailsModel : PageModel
    {
        private readonly EventsDbContext _context;

        public DetailsModel(EventsDbContext context)
        {
            _context = context;
        }

        public GuestBooking GuestBooking { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var guestbooking = await _context.GuestBookings.FirstOrDefaultAsync(m => m.EventId == id);
            if (guestbooking == null)
            {
                return NotFound();
            }
            else
            {
                GuestBooking = guestbooking;
            }
            return Page();
        }
    }
}

ThAmCo.Events/Pages/Bookings/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ThAmCo.Events.Models;

namespace ThAmCo.Events.Pages.Bookings
{
    public class EditModel : PageModel
    {
        private readonly EventsDbContext _context;

        public EditModel(EventsDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public GuestBooking GuestBooking { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var guestbooking =  await _context.GuestBookings.FirstOrDefaultAsync(m => m.EventId == id);
            if (guestbooking == null)
            {
                return NotFound();
            }
            GuestBooking = guestbooking;
           ViewData["EventId"] = new SelectList(_context.Events, "Id", "Id");
           ViewData["GuestId"] = new SelectList(_context.Guests, "Id", "Id");
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(GuestBooking).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!GuestBookingExists(GuestBooking.EventId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool GuestBookingExists(int id)
        {
            return _context.GuestBookings.Any(e => e.EventId == id);
        }
    }
}

ThAmCo.Events/Pages/EventsList/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ThAmCo.Events.Models;
using ThAmCo.Events.Models.DTO;

namespace ThAmCo.Events.Pages.EventsList
{
    public class CreateModel : PageModel
    {
        private readonly EventsDbContext _context;

        public CreateModel(EventsDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public CreateEventDTO EventDto { get; set; } = default!;

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var evnt = new Event
            {
                Title = EventDto.Title,
                Date = EventDto.Date,
                EventType = EventDto.EventType,
                IsCancelled = EventDto.IsCancelled,
                VenueId = EventDto.VenueId
            };

            _context.Events.Add(evnt);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

ThAmCo.Events/Pages/EventsList/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ThAmCo.Events.Models;

namespace ThAmCo.Events.Pages.EventsList
{
    public class DeleteModel : PageModel
    {
        private readonly EventsDbContext _context;

        public DeleteModel(EventsDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Event Event { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evnt = await _context.Events.FirstOrDefaultAsync(m => m.Id == id);

            if (evnt == null)
            {
                return NotFound();
            }
            else
            {
                Event = evnt;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evnt = await _context.Events.FindAsync(id);
            if (evnt != null)
            {
                Event = evnt;
                _context.Events.Remove(Event);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

ThAmCo.Events/Pages/EventsList/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ThAmCo.Events.Models;

namespace ThAmCo.Events.Pages.EventsList
{
    public class DetailsModel : PageModel
    {
        private readonly EventsDbContext _context;

        public DetailsModel(EventsDbContext context)
        {
            _context = context;
        }

        public Event Event { get; set; } = default!;
        public List<GuestBooking> Attendees { get; set; } = new List<GuestBooking>();

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Event = await _context.Events
                .Include(e => e.GuestBookings)
                .ThenInclude(gb => gb.Guest)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (Event == null)
            {
                return NotFound();
            }

            Attendees = Event.GuestBookings.ToList();

            return Page();
        }

        public async Task<IActionResult> OnPostRegisterAttendanceAsync(int? id, int guestId, bool isAttending)
        {
            if (id == null)
            {
                return NotFound();
            }

            Event = await _context.Events
                .Include(e => e.GuestBookings)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (Event == null)
            {
                return NotFound();
            }

            var guestBooking = Event.GuestBookings.FirstOrDefault(gb => gb.GuestId == guestId);
            if (guestBooking != null)
            {
                guestBooking.IsAttending = isAttending;
                await _context.SaveChangesAsync();
            }

            return RedirectToPage(new { id = Event.Id });
        }
    }
}

ThAmCo.Events/Pages/EventsList/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ThAmCo.Events.Models;

namespace ThAmCo.Events.Pages.EventsList
{
    public class EditModel : PageModel
    {
        private readonly EventsDbContext _context;

        public EditModel(EventsDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public EditEventDto EventDto { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evnt = await _context.Events.FirstOrDefaultAsync(m => m.Id == id);
            if (evnt == null)
            {
                return NotFound();
            }

            EventDto = new EditEventDto
            {
                Id = evnt.Id,
                Title = evnt.Title,
                VenueId = evnt.VenueId
            };

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var evnt = await _context.Events.FirstOrDefaultAsync(m => m.Id == id);
            if (evnt == null)
            {
                return NotFound();
            }

            evnt.Title = EventDto.Title;
            evnt.VenueId = EventDto.VenueId;

            _context.Attach(evnt).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!EventExists(EventDto.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool EventExists(int id)
        {
            return _context.Events.Any(e => e.Id == id);
        }
    }
}

ThAmCo.Events/Pages/EventsList/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ThAmCo.Events.Models;

namespace ThAmCo.Events.Pages.EventsList
{
    public class IndexModel : PageModel
    {
        private readonly EventsDbContext _context;

        public IndexModel(EventsDbContext context)
        {
            _context = context;
        }

        public IList<EventViewModel> Event { get; set; } = default!;

        public async Task OnGetAsync()
        {
            Event = await _context.Events
                .Include(e => e.GuestBookings)
                .ThenInclude(gb => gb.Guest)
                .Select(e => new EventViewModel
                {
                    Id = e.Id,
                    Title = e.Title,
                    Date = e.Date,
                    EventType = e.EventType,
                    IsCancelled = e.IsCancelled,
                    VenueId = e.VenueId,
                    TotalBookings = e.GuestBookings.Count(),
                    ConfirmedAttendees = e.GuestBookings.Count(gb => gb.IsAttending)
                })
                .ToListAsync();
        }

        public class EventViewModel
        {
            public int Id { get; set; }
            public string Title { get; set; }
            public DateTime Date { get; set; }
            public string EventType { get; set; }
            public bool IsCancelled { get; set; }
            public int? VenueId { get; set; }
            public int TotalBookings { get; set; }
            public int ConfirmedAttendees { get; set; }
        }
    }
}

ThAmCo.Events/Pages/Guests/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ThAmCo.Events.Models;

namespace ThAmCo.Events.Pages.Guests
{
    public class CreateModel : PageModel
    {
        private readonly EventsDbContext _context;

        public CreateModel(EventsDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Guest Guest { get; set; } = default!;

        public IActionResult OnGet()
        {
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Guests.Add(Guest);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

ThAmCo.Events/Pages/EventsList/Create.cshtml
@page
@model ThAmCo.Events.Pages.EventsList.CreateModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Event</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EventDto.Title" class="control-label"></label>
                <input asp-for="EventDto.Title" class="form-control" />
                <span asp-validation-for="EventDto.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventDto.Date" class="control-label"></label>
                <input asp-for="EventDto.Date" class="form-control" />
                <span asp-validation-for="EventDto.Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventDto.EventType" class="control-label"></label>
                <input asp-for="EventDto.EventType" class="form-control" />
                <span asp-validation-for="EventDto.EventType" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="EventDto.IsCancelled" /> @Html.DisplayNameFor(model => model.EventDto.IsCancelled)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="EventDto.VenueId" class="control-label"></label>
                <input asp-for="EventDto.VenueId" class="form-control" />
                <span asp-validation-for="EventDto.VenueId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

ThAmCo.Events/Pages/EventsList/Delete.cshtml
@page
@model ThAmCo.Events.Pages.EventsList.DeleteModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Event</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Event.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Event.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Event.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Event.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Event.EventType)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Event.EventType)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Event.IsCancelled)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Event.IsCancelled)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Event.VenueId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Event.VenueId)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Event.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

ThAmCo.Events/Pages/EventsList/Details.cshtml
@page
@model ThAmCo.Events.Pages.EventsList.DetailsModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Event</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Event.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Event.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Event.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Event.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Event.EventType)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Event.EventType)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Event.IsCancelled)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Event.IsCancelled)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Event.VenueId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Event.VenueId)
        </dd>
    </dl>
</div>

<div>
    <h4>Attendees</h4>
    <hr />
    <p>Total Attendees: @Model.Attendees.Count</p>
    <table class="table">
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Is Attending</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var attendee in Model.Attendees)
            {
                <tr>
                    <td>@attendee.Guest.Name</td>
                    <td>@attendee.Guest.Email</td>
                    <td>@(attendee.IsAttending ? "Yes" : "No")</td>
                    <td>
                        <form method="post" asp-page-handler="RegisterAttendance">
                            <input type="hidden" name="id" value="@Model.Event.Id" />
                            <input type="hidden" name="guestId" value="@attendee.GuestId" />
                            <input type="hidden" name="isAttending" value="true" />
                            <button type="submit" class="btn btn-success">Mark as Attending</button>
                        </form>
                        <form method="post" asp-page-handler="RegisterAttendance">
                            <input type="hidden" name="id" value="@Model.Event.Id" />
                            <input type="hidden" name="guestId" value="@attendee.GuestId" />
                            <input type="hidden" name="isAttending" value="false" />
                            <button type="submit" class="btn btn-danger">Mark as Not Attending</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div>
    <a asp-page="./Edit" asp-route-id="@Model.Event.Id">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

ThAmCo.Events/Pages/EventsList/Edit.cshtml
@page ""
@model ThAmCo.Events.Pages.EventsList.EditModel

<h2>Edit Event</h2>

<form method="post">
    <div class="form-group">
        <label asp-for="EventDto.Title" class="control-label"></label>
        <input asp-for="EventDto.Title" class="form-control" />
        <span asp-validation-for="EventDto.Title" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="EventDto.VenueId" class="control-label"></label>
        <input asp-for="EventDto.VenueId" class="form-control" />
        <span asp-validation-for="EventDto.VenueId" class="text-danger"></span>
    </div>
    <input type="submit" value="Save" class="btn btn-primary" />
</form>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

ThAmCo.Events/Pages/EventsList/Index.cshtml
@page
@model ThAmCo.Events.Pages.EventsList.IndexModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-page="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Event[0].Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Event[0].Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Event[0].EventType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Event[0].IsCancelled)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Event[0].VenueId)
            </th>
            <th>
                Total Bookings (Confirmed)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Event)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EventType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsCancelled)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VenueId)
                </td>
                <td>
                    @item.TotalBookings (@item.ConfirmedAttendees Confirmed)
                </td>
                <td>
                    <a asp-page="./Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-page="./Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-page="./Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>